Nodes:
  - PanelType: "ZicBoard" # Panel type: ZicBoard
    ApiConfig:
      ApiHost: "http://127.0.0.1:667"
      ApiKey: "123"
      NodeID: 41
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      RuleListPath: # /etc/ZicBoard/rulelist Path to local rulelist file
    ControllerConfig:
      EnableProxyProtocol: false
      DisableLocalREALITYConfig: false
      DeviceOnlineMinTraffic: 100
      EnableREALITY: false
      REALITYConfigs:
        Show: true
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file
        CertFile: /etc/ZicBoard/cert/zicboard_server.cert # Provided if the CertMode is file
        KeyFile: /etc/ZicBoard/cert/zicboard_server.key